# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abouchfa <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/13 20:32:24 by abouchfa          #+#    #+#              #
#    Updated: 2021/10/13 20:34:03 by abouchfa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ops.c ft_putstr.c ft_putnbr.c ft_atoi.c do-op.c
GCC = gcc -Wall -Wextra -Werror
NAME = do-op

all:
	$(GCC) -o $(NAME) $(SRC)

clean:
	rm -f *.o

fclean:
	rm -f $(NAME)
